conserver/main.c, console/console.c
I took @FauxFaux openssl 1.1 patch, added support for building with earlier openssl versions, and enabled anonymous ciphers in openssl 1.1--even though this is very dangerous, so it maintains the same functionality as earlier openssl, and lets it pass all tests.
Signed-off-by: Eneas U de Queiroz <cote2004-github@yahoo.com>
=> Openssl 1.1

conserver.cf/conserver.cf.man
Obtained from FreeBSD PR 204703.
=> Correct 'impi' typo

configure.in, conserver/cutil.c
Builds fine. configure also needs updating. More like removal actually.
=> Fix compilation without deprecated OpenSSL 1.1 APIs

configure.ac
I've been using this on OpenBSD for ages (and include it as a patch in the port), works well.
=> support SO_PEERCRED as well as ucred

conserver/consent.c, conserver/cutil.c, conserver/group.c
- Improve GSSAPI handling under FreeBSD
- Use ifr->ifr_addr instead of ifr->ifr_ifru under FreeBSD
=> FreeBSD/FreeBSD GSSAPI Fixes

conserver/consent.c
With a non-blocking socket, `connect(2)` will set `errno` to `EINPROGRESS` and the user must then fetch the success/fail status from the socket.
This was correctly handled in the IPv4 path, but not in the IPv6 path.
=> fix host consoles in combination --with-ipv6

conserver/consent.c, conserver/group.c
The former is removed in POSIX 2008.
Signed-off-by: Rosen Penev <rosenp@gmail.com>
=> replace usleep with nanosleep

console/console.c, console/readconf.h
Hello,
This commit is adding an option 'k' to make the console
application exits when the console is down.
This can be useful in some cases such as an integration to LAVA
infrastructure. Console can be used to open a terminal on different
boards to be able to run some tests.
In some cases, the console is down and without this commit, the
tests will be timed-out because it can't talk to the device.
Adding this option will allow us to exit the console directly, without
waiting for a timeout. The benefit will be time saving.
Signed-off-by: Mylène Josserand <mylene.josserand@collabora.com>
=> console: Add 'k' option to exit on console-down

conserver/access.c, conserver/consent.c, conserver/cutil.c, conserver/group.c, console/console.c
While this addresses the immediate problem, there also seems to be lack of support for the `--with-trustrevdns` when `--with-ipv6` is used.  So, this isn't perfect, but gets things closer.
=> Fix #48 - apply ipv4 CIDR access list when compiled with ipv6 support

configure.ac
This was previously reported downstream at Gentoo: https://bugs.gentoo.org/750230
autoconf-2.70 changed behavior when using `$@` in `AC_DEFINE_UNQUOTED` which results in the string getting a newline after each element and that later makes the configure run fail. Changing this to `$*` fixes the issue.
The change to `AC_PREREQ` is not really required for autoconf-2.70 (especially not settiong it to `2.69` vaule) but I could only test the fix with autoconf-2.69 and autoconf-2.70 and given that v2.69 is nearly eight years old already I don't see a problem in rasing the version requirement here.
=> configure.ac: autoconf-2.70 fix

conserver/consent.c
Linux (and others) allow higher baud rates than POSIX.
Add the definitions so that baud rates up to 4Mb/s are recognised
and can be used.
Signed-off-by: Peter Chubb <peter.chubb@data61.csiro.au>
=> Conserver-server: Add high baud rates

conserver/main.c, conserver/readcfg.c
If compiling with IPv6 support and setproctitle two places are using
the wrong type (char *) instead of (ushort) or a non-existent variable.
Fix these to make --with-ipv6 compile on FreeBSD.
=> Make compile --with-ipv6 & setproctitle

conserver.cf/conserver.cf.man.in, conserver/readcfg.c
Add a 'b' subst format to get baud rates as well to build up
device names and the others.
=> conserver.cf: devicesubst add 'b' for baud rate

conserver.cf/conserver.cf.man.in, conserver/group.c, test/results/test13, test/results/test15
When having "examine" print baud/parity increase the maximum string
width from 6 to 7 digits.  And while here try to indicate more baud
values in the manual going up to 4000000.
=> conserver: reflect that baud rates have increased to 7 digits

configure.ac
This PR tries to upstream a patch used by Fedora for many years that adds a support for `libgssapi_krb5`.
Fixes: #59
=> configure.ac: support libgssapi_krb5

conserver/group.c, conserver/master.c
`true` coming from some macos configurations is a define in `stdbool`. This
means it can't be redefined or turned into a reference.
Use a different variable name.
=> Don't reference `true`

conserver/cutil.c
We have seen conserver crash due to a buffer overflow which was tracked down to the following code in Spawn():
if (pCLmall->fd != (CONSFILE *)0) {
int fd;
fd = FileUnopen(pCLmall->fd);
pCLmall->fd = (CONSFILE *)0;
CONDDEBUG((1, "Spawn(): closing Master() client fd %d", fd));
close(fd);
*           FD_CLR(fd, &rinit);
FD_CLR(fd, &winit);
}
FileUnopen had returned -1 (which can happen for CONSFILEs of type SSLSocket), and that was passed to FD_CLR, which essentially uses it as an array index.
The signature of the crash is as follows:
*** buffer overflow detected ***: /usr/sbin/conserver terminated
======= Backtrace: =========
/lib64/libc.so.6(__fortify_fail+0x37)[0x7facde1987a7] /lib64/libc.so.6(+0x116922)[0x7facde196922]
/lib64/libc.so.6(+0x118707)[0x7facde198707] …
=> FileUnopen: always return a valid file descriptor

conserver/consent.c
When looping through addrinfo lists matching addresses, keep a copy of the original addrinfo pointers to free instead of ending up at the terminating NULLs and trying to free those.
In the best case this fixes a mem leak.  In implementations such as musl where freeaddrinfo(NULL) is not safe (which is not required by the spec), this fixes a segfault.
(I used the "rp" names to be consistent with other similar loops elsewhere in the code.)
=> In AddrsMatch, keep copies of addrinfos to free.

conserver/Makefile.in, console/Makefile.in
Currently out-of-tree build fails:
mkdir build-conserver               
cd build-conserver                  
../conserver-8.2.7/configure
make
gcc -O  -o conserver access.o client.o consent.o group.o main.o master.o readcfg.o fallback.o cutil.o -lutil -lcrypt  
/usr/bin/ld: cannot find access.o: No such file or directory
/usr/bin/ld: cannot find client.o: No such file or directory
/usr/bin/ld: cannot find consent.o: No such file or directory
/usr/bin/ld: cannot find group.o: No such file or directory
/usr/bin/ld: cannot find main.o: No such file or directory
/usr/bin/ld: cannot find master.o: No such file or directory
/usr/bin/ld: cannot find readcfg.o: No such file or directory
/usr/bin/ld: cannot find fallback.o: No such file or directory
/usr/bin/ld: cannot find cutil.o: No such file …
=> Fix failure of out-of-tree build

conserver/group.c
This patch prevents console clients started explicitly in spy mode (e.g., console -s victim) from being promoted to console writer after a preexisting writer disconnects.  It also makes the server produce more useful error messages when issued commands that cannot be executed while in spy mode.
See issue 107 https://github.com/bstansell/conserver/issues/107.
=> Prevent spy-mode clients (i.e., console -s ...) from being promoted to console writer

conserver/cutil.c
String alloc management debug messages are way too noisy and get in the
way of more important debugging tasks.
=> reduce level of string alloc management debug messages

conserver.cf/conserver.cf.man.in, conserver/group.c, conserver/main.c, conserver/readcfg.c, conserver/readcfg.h, test/test1.cf
Add support for specifying `reinitcheck` in seconds instead of default minutes. If no unit is specified, minutes are used for backward compatibility.
Rationale:
If target system comes from down to up sometimes waiting for >1min to reinit the connection is not acceptable as some early boot messages or prompts can be lost.
=> conserver.cf: second resolution for reinitcheck

conserver/client.h, conserver/group.c, console/console.c
Kerberos ticket may include additional authorization data (AD) information. With MIT Kerberos 1.21 a minimal PAC AD is included. In Active Directory or FreeIPA environments where a full PAC AD is available, the size of Kerberos ticket may be up to 64Kb.
=> Increase buffer size for GSSAPI exchanges
